### PR TITLE
Fixed stale handles being open

### PR DESCRIPTION
**Pull request by AurumTheEnd**
...which prevented overwriting FS VMs on Windows.

### CODE REVIEW

**Comment by judovana** [comment]
hi!

Great fix. Are you sure it had not killed the FS support and nested jars?
There was issue - may be unrelated - that closing the streams ahead of time was (of course) killing the access to the nested jar.

**Comment by AurumTheEnd** [comment]
> hi!
> 
> Great fix. Are you sure it had not killed the FS support and nested jars?
> There was issue - may be unrelated - that closing the streams ahead of time was (of course) killing the access to the nested jar.

Tested this on both Linux and Windows, but only using a regular JAR (since it prevented FS overwrites working at all in Windows). Will continue with nested jars tomorrow. I already consulted @ilbinek today since half the code I was sifting through was his, so I can only ask some more: @ilbinek, do you feel that these changes anyhow relate to your earlier stream-closing issues?

**Comment by judovana** [comment]
Yup. Test with nested jar is necessary. I used jenkins.war in my last tests :)
How possible spotbugs had not found it?

**Comment by judovana** [comment]
Quick check shows it seesm to be working on nested jar. merging. But feel free to discus!

**Pull request merged**
