### PR TITLE
Post initClass fixes

### PR DESCRIPTION
**Pull request by AurumTheEnd**

### CODE REVIEW

**Comment by judovana** [comment]
wtf?

**Comment by judovana** [comment]
nice. ty! oNly the title....

**Comment by judovana** [comment]
why WIP?

**Comment by AurumTheEnd** [comment]
> wtf?

?

**Comment by judovana** [comment]
> > wtf?
> 
> ?

The title was misleading.

**Comment by judovana** [comment]
> > why WIP?
> 
> Because I didn't have the time to rebase master into it.

Yah. Sorry for merging, I started to work on  LIST_OVERRIDES and REMOVE_OVERRIDE agent actions and found that it will have huge intersection. I have it nearly finsihed and so I merged this work so I could built mine o that.

Btw, never use github ui for merging. It did terrible things, but was interesting experiment.

**Comment by judovana** [comment]
> > > why WIP?
> > 
> > 
> > Because I didn't have the time to rebase master into it.
> 
> Yah. Sorry for merging, I started to work on LIST_OVERRIDES and REMOVE_OVERRIDE agent actions and found that it will 

I have ti finished. Just need t split it to more commits. .. agian

**Pull request merged**
